package grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetCapacityReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetCapacityReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string client_id = 1;</code>
     * @return The clientId.
     */
    String getClientId();
    /**
     * <code>string client_id = 1;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string resource_id = 2;</code>
     * @return The resourceId.
     */
    String getResourceId();
    /**
     * <code>string resource_id = 2;</code>
     * @return The bytes for resourceId.
     */
    com.google.protobuf.ByteString
        getResourceIdBytes();

    /**
     * <pre>
     * 需要的配额
     * </pre>
     *
     * <code>double wants = 3;</code>
     * @return The wants.
     */
    double getWants();
  }
  /**
   * Protobuf type {@code GetCapacityReq}
   */
  public static final class GetCapacityReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetCapacityReq)
      GetCapacityReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetCapacityReq.newBuilder() to construct.
    private GetCapacityReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetCapacityReq() {
      clientId_ = "";
      resourceId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetCapacityReq();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetCapacityReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              resourceId_ = s;
              break;
            }
            case 25: {

              wants_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Api.internal_static_GetCapacityReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Api.internal_static_GetCapacityReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetCapacityReq.class, Builder.class);
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 1;
    private volatile Object clientId_;
    /**
     * <code>string client_id = 1;</code>
     * @return The clientId.
     */
    @Override
    public String getClientId() {
      Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string client_id = 1;</code>
     * @return The bytes for clientId.
     */
    @Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESOURCE_ID_FIELD_NUMBER = 2;
    private volatile Object resourceId_;
    /**
     * <code>string resource_id = 2;</code>
     * @return The resourceId.
     */
    @Override
    public String getResourceId() {
      Object ref = resourceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resourceId_ = s;
        return s;
      }
    }
    /**
     * <code>string resource_id = 2;</code>
     * @return The bytes for resourceId.
     */
    @Override
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      Object ref = resourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WANTS_FIELD_NUMBER = 3;
    private double wants_;
    /**
     * <pre>
     * 需要的配额
     * </pre>
     *
     * <code>double wants = 3;</code>
     * @return The wants.
     */
    @Override
    public double getWants() {
      return wants_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!getResourceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resourceId_);
      }
      if (wants_ != 0D) {
        output.writeDouble(3, wants_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!getResourceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resourceId_);
      }
      if (wants_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, wants_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetCapacityReq)) {
        return super.equals(obj);
      }
      GetCapacityReq other = (GetCapacityReq) obj;

      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getResourceId()
          .equals(other.getResourceId())) return false;
      if (Double.doubleToLongBits(getWants())
          != Double.doubleToLongBits(
              other.getWants())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + RESOURCE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getResourceId().hashCode();
      hash = (37 * hash) + WANTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getWants()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetCapacityReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetCapacityReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetCapacityReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetCapacityReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetCapacityReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetCapacityReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetCapacityReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetCapacityReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetCapacityReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetCapacityReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetCapacityReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetCapacityReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetCapacityReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetCapacityReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetCapacityReq)
        GetCapacityReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Api.internal_static_GetCapacityReq_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Api.internal_static_GetCapacityReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetCapacityReq.class, Builder.class);
      }

      // Construct using Api.GetCapacityReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        clientId_ = "";

        resourceId_ = "";

        wants_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Api.internal_static_GetCapacityReq_descriptor;
      }

      @Override
      public GetCapacityReq getDefaultInstanceForType() {
        return GetCapacityReq.getDefaultInstance();
      }

      @Override
      public GetCapacityReq build() {
        GetCapacityReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GetCapacityReq buildPartial() {
        GetCapacityReq result = new GetCapacityReq(this);
        result.clientId_ = clientId_;
        result.resourceId_ = resourceId_;
        result.wants_ = wants_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetCapacityReq) {
          return mergeFrom((GetCapacityReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetCapacityReq other) {
        if (other == GetCapacityReq.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getResourceId().isEmpty()) {
          resourceId_ = other.resourceId_;
          onChanged();
        }
        if (other.getWants() != 0D) {
          setWants(other.getWants());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetCapacityReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetCapacityReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object clientId_ = "";
      /**
       * <code>string client_id = 1;</code>
       * @return The clientId.
       */
      public String getClientId() {
        Object ref = clientId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string client_id = 1;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_id = 1;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 1;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private Object resourceId_ = "";
      /**
       * <code>string resource_id = 2;</code>
       * @return The resourceId.
       */
      public String getResourceId() {
        Object ref = resourceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resourceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string resource_id = 2;</code>
       * @return The bytes for resourceId.
       */
      public com.google.protobuf.ByteString
          getResourceIdBytes() {
        Object ref = resourceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resourceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resource_id = 2;</code>
       * @param value The resourceId to set.
       * @return This builder for chaining.
       */
      public Builder setResourceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resource_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResourceId() {
        
        resourceId_ = getDefaultInstance().getResourceId();
        onChanged();
        return this;
      }
      /**
       * <code>string resource_id = 2;</code>
       * @param value The bytes for resourceId to set.
       * @return This builder for chaining.
       */
      public Builder setResourceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resourceId_ = value;
        onChanged();
        return this;
      }

      private double wants_ ;
      /**
       * <pre>
       * 需要的配额
       * </pre>
       *
       * <code>double wants = 3;</code>
       * @return The wants.
       */
      @Override
      public double getWants() {
        return wants_;
      }
      /**
       * <pre>
       * 需要的配额
       * </pre>
       *
       * <code>double wants = 3;</code>
       * @param value The wants to set.
       * @return This builder for chaining.
       */
      public Builder setWants(double value) {
        
        wants_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 需要的配额
       * </pre>
       *
       * <code>double wants = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWants() {
        
        wants_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetCapacityReq)
    }

    // @@protoc_insertion_point(class_scope:GetCapacityReq)
    private static final GetCapacityReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetCapacityReq();
    }

    public static GetCapacityReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCapacityReq>
        PARSER = new com.google.protobuf.AbstractParser<GetCapacityReq>() {
      @Override
      public GetCapacityReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetCapacityReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetCapacityReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetCapacityReq> getParserForType() {
      return PARSER;
    }

    @Override
    public GetCapacityReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetCapacityRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetCapacityResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 资源id
     * </pre>
     *
     * <code>string resource_id = 1;</code>
     * @return The resourceId.
     */
    String getResourceId();
    /**
     * <pre>
     * 资源id
     * </pre>
     *
     * <code>string resource_id = 1;</code>
     * @return The bytes for resourceId.
     */
    com.google.protobuf.ByteString
        getResourceIdBytes();

    /**
     * <pre>
     * 刷新间隔(秒)
     * </pre>
     *
     * <code>int64 refresh_interval = 2;</code>
     * @return The refreshInterval.
     */
    long getRefreshInterval();

    /**
     * <pre>
     * 分配的容量
     * </pre>
     *
     * <code>double gets = 3;</code>
     * @return The gets.
     */
    double getGets();

    /**
     * <pre>
     * 可以借用的容量
     * </pre>
     *
     * <code>double reserve = 4;</code>
     * @return The reserve.
     */
    double getReserve();
  }
  /**
   * Protobuf type {@code GetCapacityResp}
   */
  public static final class GetCapacityResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GetCapacityResp)
      GetCapacityRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetCapacityResp.newBuilder() to construct.
    private GetCapacityResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetCapacityResp() {
      resourceId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetCapacityResp();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetCapacityResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              resourceId_ = s;
              break;
            }
            case 16: {

              refreshInterval_ = input.readInt64();
              break;
            }
            case 25: {

              gets_ = input.readDouble();
              break;
            }
            case 33: {

              reserve_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Api.internal_static_GetCapacityResp_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Api.internal_static_GetCapacityResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetCapacityResp.class, Builder.class);
    }

    public static final int RESOURCE_ID_FIELD_NUMBER = 1;
    private volatile Object resourceId_;
    /**
     * <pre>
     * 资源id
     * </pre>
     *
     * <code>string resource_id = 1;</code>
     * @return The resourceId.
     */
    @Override
    public String getResourceId() {
      Object ref = resourceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resourceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 资源id
     * </pre>
     *
     * <code>string resource_id = 1;</code>
     * @return The bytes for resourceId.
     */
    @Override
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      Object ref = resourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFRESH_INTERVAL_FIELD_NUMBER = 2;
    private long refreshInterval_;
    /**
     * <pre>
     * 刷新间隔(秒)
     * </pre>
     *
     * <code>int64 refresh_interval = 2;</code>
     * @return The refreshInterval.
     */
    @Override
    public long getRefreshInterval() {
      return refreshInterval_;
    }

    public static final int GETS_FIELD_NUMBER = 3;
    private double gets_;
    /**
     * <pre>
     * 分配的容量
     * </pre>
     *
     * <code>double gets = 3;</code>
     * @return The gets.
     */
    @Override
    public double getGets() {
      return gets_;
    }

    public static final int RESERVE_FIELD_NUMBER = 4;
    private double reserve_;
    /**
     * <pre>
     * 可以借用的容量
     * </pre>
     *
     * <code>double reserve = 4;</code>
     * @return The reserve.
     */
    @Override
    public double getReserve() {
      return reserve_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResourceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resourceId_);
      }
      if (refreshInterval_ != 0L) {
        output.writeInt64(2, refreshInterval_);
      }
      if (gets_ != 0D) {
        output.writeDouble(3, gets_);
      }
      if (reserve_ != 0D) {
        output.writeDouble(4, reserve_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResourceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resourceId_);
      }
      if (refreshInterval_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, refreshInterval_);
      }
      if (gets_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, gets_);
      }
      if (reserve_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, reserve_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GetCapacityResp)) {
        return super.equals(obj);
      }
      GetCapacityResp other = (GetCapacityResp) obj;

      if (!getResourceId()
          .equals(other.getResourceId())) return false;
      if (getRefreshInterval()
          != other.getRefreshInterval()) return false;
      if (Double.doubleToLongBits(getGets())
          != Double.doubleToLongBits(
              other.getGets())) return false;
      if (Double.doubleToLongBits(getReserve())
          != Double.doubleToLongBits(
              other.getReserve())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESOURCE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getResourceId().hashCode();
      hash = (37 * hash) + REFRESH_INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRefreshInterval());
      hash = (37 * hash) + GETS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getGets()));
      hash = (37 * hash) + RESERVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getReserve()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GetCapacityResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetCapacityResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetCapacityResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetCapacityResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetCapacityResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetCapacityResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetCapacityResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetCapacityResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetCapacityResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GetCapacityResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GetCapacityResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GetCapacityResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GetCapacityResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetCapacityResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetCapacityResp)
        GetCapacityRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Api.internal_static_GetCapacityResp_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Api.internal_static_GetCapacityResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetCapacityResp.class, Builder.class);
      }

      // Construct using Api.GetCapacityResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        resourceId_ = "";

        refreshInterval_ = 0L;

        gets_ = 0D;

        reserve_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Api.internal_static_GetCapacityResp_descriptor;
      }

      @Override
      public GetCapacityResp getDefaultInstanceForType() {
        return GetCapacityResp.getDefaultInstance();
      }

      @Override
      public GetCapacityResp build() {
        GetCapacityResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GetCapacityResp buildPartial() {
        GetCapacityResp result = new GetCapacityResp(this);
        result.resourceId_ = resourceId_;
        result.refreshInterval_ = refreshInterval_;
        result.gets_ = gets_;
        result.reserve_ = reserve_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetCapacityResp) {
          return mergeFrom((GetCapacityResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetCapacityResp other) {
        if (other == GetCapacityResp.getDefaultInstance()) return this;
        if (!other.getResourceId().isEmpty()) {
          resourceId_ = other.resourceId_;
          onChanged();
        }
        if (other.getRefreshInterval() != 0L) {
          setRefreshInterval(other.getRefreshInterval());
        }
        if (other.getGets() != 0D) {
          setGets(other.getGets());
        }
        if (other.getReserve() != 0D) {
          setReserve(other.getReserve());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetCapacityResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetCapacityResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object resourceId_ = "";
      /**
       * <pre>
       * 资源id
       * </pre>
       *
       * <code>string resource_id = 1;</code>
       * @return The resourceId.
       */
      public String getResourceId() {
        Object ref = resourceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resourceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 资源id
       * </pre>
       *
       * <code>string resource_id = 1;</code>
       * @return The bytes for resourceId.
       */
      public com.google.protobuf.ByteString
          getResourceIdBytes() {
        Object ref = resourceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resourceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 资源id
       * </pre>
       *
       * <code>string resource_id = 1;</code>
       * @param value The resourceId to set.
       * @return This builder for chaining.
       */
      public Builder setResourceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 资源id
       * </pre>
       *
       * <code>string resource_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResourceId() {
        
        resourceId_ = getDefaultInstance().getResourceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 资源id
       * </pre>
       *
       * <code>string resource_id = 1;</code>
       * @param value The bytes for resourceId to set.
       * @return This builder for chaining.
       */
      public Builder setResourceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resourceId_ = value;
        onChanged();
        return this;
      }

      private long refreshInterval_ ;
      /**
       * <pre>
       * 刷新间隔(秒)
       * </pre>
       *
       * <code>int64 refresh_interval = 2;</code>
       * @return The refreshInterval.
       */
      @Override
      public long getRefreshInterval() {
        return refreshInterval_;
      }
      /**
       * <pre>
       * 刷新间隔(秒)
       * </pre>
       *
       * <code>int64 refresh_interval = 2;</code>
       * @param value The refreshInterval to set.
       * @return This builder for chaining.
       */
      public Builder setRefreshInterval(long value) {
        
        refreshInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 刷新间隔(秒)
       * </pre>
       *
       * <code>int64 refresh_interval = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRefreshInterval() {
        
        refreshInterval_ = 0L;
        onChanged();
        return this;
      }

      private double gets_ ;
      /**
       * <pre>
       * 分配的容量
       * </pre>
       *
       * <code>double gets = 3;</code>
       * @return The gets.
       */
      @Override
      public double getGets() {
        return gets_;
      }
      /**
       * <pre>
       * 分配的容量
       * </pre>
       *
       * <code>double gets = 3;</code>
       * @param value The gets to set.
       * @return This builder for chaining.
       */
      public Builder setGets(double value) {
        
        gets_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 分配的容量
       * </pre>
       *
       * <code>double gets = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGets() {
        
        gets_ = 0D;
        onChanged();
        return this;
      }

      private double reserve_ ;
      /**
       * <pre>
       * 可以借用的容量
       * </pre>
       *
       * <code>double reserve = 4;</code>
       * @return The reserve.
       */
      @Override
      public double getReserve() {
        return reserve_;
      }
      /**
       * <pre>
       * 可以借用的容量
       * </pre>
       *
       * <code>double reserve = 4;</code>
       * @param value The reserve to set.
       * @return This builder for chaining.
       */
      public Builder setReserve(double value) {
        
        reserve_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可以借用的容量
       * </pre>
       *
       * <code>double reserve = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReserve() {
        
        reserve_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GetCapacityResp)
    }

    // @@protoc_insertion_point(class_scope:GetCapacityResp)
    private static final GetCapacityResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GetCapacityResp();
    }

    public static GetCapacityResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetCapacityResp>
        PARSER = new com.google.protobuf.AbstractParser<GetCapacityResp>() {
      @Override
      public GetCapacityResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetCapacityResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetCapacityResp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetCapacityResp> getParserForType() {
      return PARSER;
    }

    @Override
    public GetCapacityResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReleaseCapacityReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReleaseCapacityReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string client_id = 1;</code>
     * @return The clientId.
     */
    String getClientId();
    /**
     * <code>string client_id = 1;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string resource_id = 2;</code>
     * @return The resourceId.
     */
    String getResourceId();
    /**
     * <code>string resource_id = 2;</code>
     * @return The bytes for resourceId.
     */
    com.google.protobuf.ByteString
        getResourceIdBytes();
  }
  /**
   * Protobuf type {@code ReleaseCapacityReq}
   */
  public static final class ReleaseCapacityReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReleaseCapacityReq)
      ReleaseCapacityReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReleaseCapacityReq.newBuilder() to construct.
    private ReleaseCapacityReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReleaseCapacityReq() {
      clientId_ = "";
      resourceId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReleaseCapacityReq();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReleaseCapacityReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              resourceId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Api.internal_static_ReleaseCapacityReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Api.internal_static_ReleaseCapacityReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReleaseCapacityReq.class, Builder.class);
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 1;
    private volatile Object clientId_;
    /**
     * <code>string client_id = 1;</code>
     * @return The clientId.
     */
    @Override
    public String getClientId() {
      Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string client_id = 1;</code>
     * @return The bytes for clientId.
     */
    @Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESOURCE_ID_FIELD_NUMBER = 2;
    private volatile Object resourceId_;
    /**
     * <code>string resource_id = 2;</code>
     * @return The resourceId.
     */
    @Override
    public String getResourceId() {
      Object ref = resourceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resourceId_ = s;
        return s;
      }
    }
    /**
     * <code>string resource_id = 2;</code>
     * @return The bytes for resourceId.
     */
    @Override
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      Object ref = resourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!getResourceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resourceId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!getResourceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resourceId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReleaseCapacityReq)) {
        return super.equals(obj);
      }
      ReleaseCapacityReq other = (ReleaseCapacityReq) obj;

      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getResourceId()
          .equals(other.getResourceId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + RESOURCE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getResourceId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReleaseCapacityReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReleaseCapacityReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReleaseCapacityReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReleaseCapacityReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReleaseCapacityReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReleaseCapacityReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReleaseCapacityReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReleaseCapacityReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReleaseCapacityReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReleaseCapacityReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReleaseCapacityReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReleaseCapacityReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReleaseCapacityReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReleaseCapacityReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReleaseCapacityReq)
        ReleaseCapacityReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Api.internal_static_ReleaseCapacityReq_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Api.internal_static_ReleaseCapacityReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReleaseCapacityReq.class, Builder.class);
      }

      // Construct using Api.ReleaseCapacityReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        clientId_ = "";

        resourceId_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Api.internal_static_ReleaseCapacityReq_descriptor;
      }

      @Override
      public ReleaseCapacityReq getDefaultInstanceForType() {
        return ReleaseCapacityReq.getDefaultInstance();
      }

      @Override
      public ReleaseCapacityReq build() {
        ReleaseCapacityReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ReleaseCapacityReq buildPartial() {
        ReleaseCapacityReq result = new ReleaseCapacityReq(this);
        result.clientId_ = clientId_;
        result.resourceId_ = resourceId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReleaseCapacityReq) {
          return mergeFrom((ReleaseCapacityReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReleaseCapacityReq other) {
        if (other == ReleaseCapacityReq.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getResourceId().isEmpty()) {
          resourceId_ = other.resourceId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReleaseCapacityReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReleaseCapacityReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object clientId_ = "";
      /**
       * <code>string client_id = 1;</code>
       * @return The clientId.
       */
      public String getClientId() {
        Object ref = clientId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string client_id = 1;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_id = 1;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 1;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private Object resourceId_ = "";
      /**
       * <code>string resource_id = 2;</code>
       * @return The resourceId.
       */
      public String getResourceId() {
        Object ref = resourceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resourceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string resource_id = 2;</code>
       * @return The bytes for resourceId.
       */
      public com.google.protobuf.ByteString
          getResourceIdBytes() {
        Object ref = resourceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resourceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resource_id = 2;</code>
       * @param value The resourceId to set.
       * @return This builder for chaining.
       */
      public Builder setResourceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resourceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resource_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResourceId() {
        
        resourceId_ = getDefaultInstance().getResourceId();
        onChanged();
        return this;
      }
      /**
       * <code>string resource_id = 2;</code>
       * @param value The bytes for resourceId to set.
       * @return This builder for chaining.
       */
      public Builder setResourceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resourceId_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReleaseCapacityReq)
    }

    // @@protoc_insertion_point(class_scope:ReleaseCapacityReq)
    private static final ReleaseCapacityReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReleaseCapacityReq();
    }

    public static ReleaseCapacityReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReleaseCapacityReq>
        PARSER = new com.google.protobuf.AbstractParser<ReleaseCapacityReq>() {
      @Override
      public ReleaseCapacityReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReleaseCapacityReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReleaseCapacityReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReleaseCapacityReq> getParserForType() {
      return PARSER;
    }

    @Override
    public ReleaseCapacityReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReleaseCapacityRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReleaseCapacityResp)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code ReleaseCapacityResp}
   */
  public static final class ReleaseCapacityResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReleaseCapacityResp)
      ReleaseCapacityRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReleaseCapacityResp.newBuilder() to construct.
    private ReleaseCapacityResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReleaseCapacityResp() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReleaseCapacityResp();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReleaseCapacityResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Api.internal_static_ReleaseCapacityResp_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Api.internal_static_ReleaseCapacityResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReleaseCapacityResp.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReleaseCapacityResp)) {
        return super.equals(obj);
      }
      ReleaseCapacityResp other = (ReleaseCapacityResp) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReleaseCapacityResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReleaseCapacityResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReleaseCapacityResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReleaseCapacityResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReleaseCapacityResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReleaseCapacityResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReleaseCapacityResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReleaseCapacityResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReleaseCapacityResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReleaseCapacityResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReleaseCapacityResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReleaseCapacityResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReleaseCapacityResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReleaseCapacityResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReleaseCapacityResp)
        ReleaseCapacityRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Api.internal_static_ReleaseCapacityResp_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Api.internal_static_ReleaseCapacityResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReleaseCapacityResp.class, Builder.class);
      }

      // Construct using Api.ReleaseCapacityResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Api.internal_static_ReleaseCapacityResp_descriptor;
      }

      @Override
      public ReleaseCapacityResp getDefaultInstanceForType() {
        return ReleaseCapacityResp.getDefaultInstance();
      }

      @Override
      public ReleaseCapacityResp build() {
        ReleaseCapacityResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ReleaseCapacityResp buildPartial() {
        ReleaseCapacityResp result = new ReleaseCapacityResp(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReleaseCapacityResp) {
          return mergeFrom((ReleaseCapacityResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReleaseCapacityResp other) {
        if (other == ReleaseCapacityResp.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReleaseCapacityResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReleaseCapacityResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReleaseCapacityResp)
    }

    // @@protoc_insertion_point(class_scope:ReleaseCapacityResp)
    private static final ReleaseCapacityResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReleaseCapacityResp();
    }

    public static ReleaseCapacityResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReleaseCapacityResp>
        PARSER = new com.google.protobuf.AbstractParser<ReleaseCapacityResp>() {
      @Override
      public ReleaseCapacityResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReleaseCapacityResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReleaseCapacityResp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReleaseCapacityResp> getParserForType() {
      return PARSER;
    }

    @Override
    public ReleaseCapacityResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCapacityReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCapacityReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCapacityResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCapacityResp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReleaseCapacityReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReleaseCapacityReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReleaseCapacityResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReleaseCapacityResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tapi.proto\"G\n\016GetCapacityReq\022\021\n\tclient_" +
      "id\030\001 \001(\t\022\023\n\013resource_id\030\002 \001(\t\022\r\n\005wants\030\003" +
      " \001(\001\"_\n\017GetCapacityResp\022\023\n\013resource_id\030\001" +
      " \001(\t\022\030\n\020refresh_interval\030\002 \001(\003\022\014\n\004gets\030\003" +
      " \001(\001\022\017\n\007reserve\030\004 \001(\001\"<\n\022ReleaseCapacity" +
      "Req\022\021\n\tclient_id\030\001 \001(\t\022\023\n\013resource_id\030\002 " +
      "\001(\t\"\025\n\023ReleaseCapacityResp2w\n\005Quota\0220\n\013G" +
      "etCapacity\022\017.GetCapacityReq\032\020.GetCapacit" +
      "yResp\022<\n\017ReleaseCapacity\022\023.ReleaseCapaci" +
      "tyReq\032\024.ReleaseCapacityRespb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetCapacityReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetCapacityReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCapacityReq_descriptor,
        new String[] { "ClientId", "ResourceId", "Wants", });
    internal_static_GetCapacityResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetCapacityResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCapacityResp_descriptor,
        new String[] { "ResourceId", "RefreshInterval", "Gets", "Reserve", });
    internal_static_ReleaseCapacityReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReleaseCapacityReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReleaseCapacityReq_descriptor,
        new String[] { "ClientId", "ResourceId", });
    internal_static_ReleaseCapacityResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ReleaseCapacityResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReleaseCapacityResp_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
